steps:
  # Pull most recent image (caching)
  #  - MUST use `entrypoint: 'bash'` to avoid exit error when image doesn't exist yet (1st build)
  - id: pull-existing-image
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/powwater/powwater_vendorsdashboard || exit 0"]
  # Add the config secret to the Container
  - id: add-config-secret
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud secrets --project=powwater versions access latest --secret=config_powwater_vendorsdashboard --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/config.yml",
      ]
  # Build the container image
  - id: build-image
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "R_CONFIG_ACTIVE=production",
        "-t",
        "gcr.io/powwater/powwater_vendorsdashboard",
        "--cache-from",
        "gcr.io/powwater/powwater_vendorsdashboard:latest",
        ".",
      ]
  # Push the Container Image to GCR
  - id: push-image
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/powwater/powwater_vendorsdashboard"]
  # Gradually Roll Out to Cloud Run w/ `TAG_NAME` (0% Traffic)
  - id: pre-deploy-no-traffic
    # NOTE:
    #   - Remove `--no-traffic` rule for 1st service deployment (or else error & failed build)
    #   - Use `--no-traffic` after 1st service deployment for testing newest deployment
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "beta",
        "run",
        "deploy",
        "powwater-vendorsdashboard",
        "--image",
        "gcr.io/powwater/powwater_vendorsdashboard",
        "--no-traffic",
        "--tag",
        "pre-deploy",
        "--add-cloudsql-instances",
        "powwater:asia-south1:powwater",
        "--region",
        "asia-east1",
        "--platform",
        "managed",
        "--timeout=3600",
        "--concurrency=250",
        "--min-instances=0",
        "--allow-unauthenticated",
      ]
  # Deploy container image to Cloud Run (Production) w/o Traffic
  - id: prod-deploy-no-traffic
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "beta",
        "run",
        "deploy",
        "powwater-vendorsdashboard",
        "--image",
        "gcr.io/powwater/powwater_vendorsdashboard",
        "--no-traffic",
        "--add-cloudsql-instances",
        "powwater:asia-south1:powwater",
        "--region",
        "asia-east1",
        "--platform",
        "managed",
        "--timeout=3600",
        "--concurrency=250",
        "--min-instances=1",
        "--max-instances=1",
        "--allow-unauthenticated",
      ]
  # Send all traffic to new Production Deployment
  - id: prod-deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "beta",
        "run",
        "services",
        "update-traffic",
        "powwater-vendorsdashboard",
        "--to-latest",
        "--region",
        "asia-east1",
        "--platform",
        "managed",
      ]
timeout: 1800s
