--- 
title: "{gitdown} report"
author: "Jimmy Briggs"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
description: "{gitdown} report for package ."
---
# Gitbook for vendor_dashboard{-} 


Done on: 2021-03-16 17:04:27





# Section: Issues
## Summary table

|Issues            |Commits links                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|:-----------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|#2                |[add orders table for #2](#issues-2-00f43cf445c0d8a1190a8372802c7ca64b0f52e9), [adjust orders for #2](#issues-2-b0ea4c24ec5702270221c1b5456f2fc4e2ccbb30)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|#3                |[add average overall vendor rating for #3](#issues-3-8a5960d5645ce1f5f66e036a7e1098b4195e4b5d)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|#4                |[add tests module and interface for #4](#issues-4-c6b0fcaf5adf4a7556a6ce5492b73704a48d13aa)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|#5                |[add inventory module and interface for #5](#issues-5-a3d0d89bd503d9836b13e9eda822be0448cc5f4e), [Vendor Inventory (#8)](#issues-5-7f4aafc864aed34a580169e9a17d6fb59d66a7cc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|#6                |[adjust maps and layout for #6](#issues-6-d9f458b43cde841553bf97e22c4e6e7c8d11def6)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|#8                |[Vendor Inventory (#8)](#issues-8-7f4aafc864aed34a580169e9a17d6fb59d66a7cc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|#9                |[#9 - minimal document upload client-side functionality](#issues-9-ea97cded1a7517c4a75e4c5e3dc04047a18d8a69), [Vendor Inventory (#8)](#issues-9-7f4aafc864aed34a580169e9a17d6fb59d66a7cc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|#11               |[fix tests for #11](#issues-11-4110d6f4f76c7c8b190b5aa9ee8c12d30f773a98), [Vendor Inventory (#8)](#issues-11-7f4aafc864aed34a580169e9a17d6fb59d66a7cc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|#12               |[create orders-module js for #12](#issues-12-e11b5bee0c22e1839b3fb958649bfc379287d2cc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|#13               |[Order Routes (#13)](#issues-13-e5b30be63f0768451673c54daf907b8162f22305)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|#14               |[add get-config.R (#14)](#issues-14-d599eba18a3bc6a159ae9f0f606c2ea52cc10905)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|#15               |[Initial Deployment (#15)](#issues-15-645987b96367b55db011a3fc0eda6f17687f518f)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|#17               |[#17 - fix customers table and added utility function](#issues-17-a08259ba0bd8a8898882135b90e7a11e316a924b), [Initial Deployment (#15)](#issues-17-645987b96367b55db011a3fc0eda6f17687f518f), [Miscellaneous (#18)](#issues-17-d6735b78ac20bbaaba207688de4ac63d8e54d8b9), [PowPolished and Enhancements (#22)](#issues-17-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|#18               |[Miscellaneous (#18)](#issues-18-d6735b78ac20bbaaba207688de4ac63d8e54d8b9)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|#20               |[#20 - powpolished migration](#issues-20-e6f7507591870173e588ab26458d77d8457ecc8c), [PowPolished and Enhancements (#22)](#issues-20-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|#21               |[#21 - add customers mapping functionalities - still WIP but works](#issues-21-7df8ea4f55e3975e9df35a9b46633c379cb453fd), [PowPolished and Enhancements (#22)](#issues-21-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|#22               |[PowPolished and Enhancements (#22)](#issues-22-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|No related issues |[Initial commit](#issues-na-1114084b1c3bfeb11e4b2405ee0afa46f25acaad), [initial scaffolding](#issues-na-effe4b5adc89637414c8a7f3298c869612f3d8fa), [ignore](#issues-na-e9b2289910fbe707e96ddc6fad26a9795aac7c29), [add maps](#issues-na-bac273d30c109dda0248d50d818f48d3dbc0134f), [online status - set to online for now](#issues-na-35bcc2aa31d86d4d8a210c7be26f324cdc98324a), [minor cleanup](#issues-na-ba3c39d4ed6e166cd038824585e3b44bdb56d602), [adjust colWidths](#issues-na-d5222eb60799c58de67837c22bb47a8d07413a90), [add-offering button for UI](#issues-na-002afe2d9bb7f27df62bbe52cf148b9075c4a1b7), [add/edit functionality for inventory offerings](#issues-na-6a8394f5db1b0f354a305608762bd795c373680d), [create choices list](#issues-na-981f81ef654e595e5bc6d392cac249d55727fb52), [adjust customer table colnames](#issues-na-1888d7e592551be49fe66c6d13da1ac3be2046d8), [added quantity to inventory as well as input validation](#issues-na-35c0a10a3938b5963bcd53529757128183efb526), [Merge branch 'develop' into main](#issues-na-294a43462dac134f0aa83520920b35165aba05d2), [dev scripts](#issues-na-594972f104944203fc236cdc6d86e3f4b919b4fb), [deploy script](#issues-na-a54e858721d62e71262d50f7e7d2019f9640c585), [artifacts from deploy script](#issues-na-3e39b7e7d1b230bfaa7394912681595d8f811079), [adminportal to vendorsdashboard](#issues-na-4d5f28d2afa674b82021d2c61175784640f02503), [add github and dockerhub registries to deployment](#issues-na-9fb77746b2acf7f1357ef821ef05a171eab95b41), [fix polished version locally](#issues-na-674ca4fb5d65783036a60e3ca516f4e84ff4933a), [Update README.md](#issues-na-edfbc40b2d217f6057cff0d9b73d9e1c0856f331), [split out gcloud-deploy](#issues-na-1e783375c71e11c1a9dab6a6b7343fc5c71ded69), [fix dockerhub push](#issues-na-bc6864ad53307cefc1d076a85d0eb58be00d5ee7), [dev misc](#issues-na-58fc0c3780117e4ed68b0602a5775998ea1ae1e1), [add profile to docs](#issues-na-c9e587c536f5e0b84a0715f2d2cee304043aea3b), [add utils](#issues-na-5dc128845ff51408c5b239efdcab458f6fd32dca), [phone-input](#issues-na-fd52f8fab9e2b7abc275c543e1af5e417871a77c), [for merge conflicts](#issues-na-191274e01a49bd852c771fe8384b7d7a1e4678b3), [bugfixes](#issues-na-65a5faa7faac51cc434a10241b7dccd6f0146f69), [Merge branch 'main' into develop](#issues-na-f43ee8c955492e816db2b08921dc437984859ed7), [Merge remote-tracking branch 'origin/main' into main](#issues-na-277d80c13fdfd3f44304e3144140f2a2f447cdf2), [error from merge](#issues-na-b4d581b98f2754bd2e4c3d13601e82363b37c83f), [Merge branch 'develop' into main](#issues-na-8215dba365aee50a105e67b9b2b1fa1a4cd7b173) |

## Issue: #2{#issues-2}

### commit: add orders table for #2{#issues-2-00f43cf445c0d8a1190a8372802c7ca64b0f52e9}

- Commit number: 00f43cf445c0d8a1190a8372802c7ca64b0f52e9
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 15:02:43
- Message content:
```
add orders table for #2


```
- Related patterns:
  + Issues: [#2](#issues-2)

### commit: adjust orders for #2{#issues-2-b0ea4c24ec5702270221c1b5456f2fc4e2ccbb30}

- Commit number: b0ea4c24ec5702270221c1b5456f2fc4e2ccbb30
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 19:23:15
- Message content:
```
adjust orders for #2


```
- Related patterns:
  + Issues: [#2](#issues-2)

## Issue: #3{#issues-3}

### commit: add average overall vendor rating for #3{#issues-3-8a5960d5645ce1f5f66e036a7e1098b4195e4b5d}

- Commit number: 8a5960d5645ce1f5f66e036a7e1098b4195e4b5d
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 19:47:26
- Message content:
```
add average overall vendor rating for #3


```
- Related patterns:
  + Issues: [#3](#issues-3)

## Issue: #4{#issues-4}

### commit: add tests module and interface for #4{#issues-4-c6b0fcaf5adf4a7556a6ce5492b73704a48d13aa}

- Commit number: c6b0fcaf5adf4a7556a6ce5492b73704a48d13aa
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 20:01:59
- Message content:
```
add tests module and interface for #4


```
- Related patterns:
  + Issues: [#4](#issues-4)

## Issue: #5{#issues-5}

### commit: add inventory module and interface for #5{#issues-5-a3d0d89bd503d9836b13e9eda822be0448cc5f4e}

- Commit number: a3d0d89bd503d9836b13e9eda822be0448cc5f4e
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 23:17:01
- Message content:
```
add inventory module and interface for #5


```
- Related patterns:
  + Issues: [#5](#issues-5)

### commit: Vendor Inventory (#8){#issues-5-7f4aafc864aed34a580169e9a17d6fb59d66a7cc}

- Commit number: 7f4aafc864aed34a580169e9a17d6fb59d66a7cc
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-12 19:29:14
- Message content:
```
Vendor Inventory (#8)

* adjust colWidths

* add inventory module and interface for #5

* add_offering button for UI

* add/edit functionality for inventory offerings

* #9 - minimal document upload client-side functionality

* create choices list

* adjust customer table colnames

* added quantity to inventory as well as input validation

* fix tests for #11
```
- Related patterns:
  + Issues: [#8](#issues-8), [#5](#issues-5), [#9](#issues-9), [#11](#issues-11)

## Issue: #6{#issues-6}

### commit: adjust maps and layout for #6{#issues-6-d9f458b43cde841553bf97e22c4e6e7c8d11def6}

- Commit number: d9f458b43cde841553bf97e22c4e6e7c8d11def6
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 00:33:43
- Message content:
```
adjust maps and layout for #6


```
- Related patterns:
  + Issues: [#6](#issues-6)

## Issue: #8{#issues-8}

### commit: Vendor Inventory (#8){#issues-8-7f4aafc864aed34a580169e9a17d6fb59d66a7cc}

- Commit number: 7f4aafc864aed34a580169e9a17d6fb59d66a7cc
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-12 19:29:14
- Message content:
```
Vendor Inventory (#8)

* adjust colWidths

* add inventory module and interface for #5

* add_offering button for UI

* add/edit functionality for inventory offerings

* #9 - minimal document upload client-side functionality

* create choices list

* adjust customer table colnames

* added quantity to inventory as well as input validation

* fix tests for #11
```
- Related patterns:
  + Issues: [#8](#issues-8), [#5](#issues-5), [#9](#issues-9), [#11](#issues-11)

## Issue: #9{#issues-9}

### commit: #9 - minimal document upload client-side functionality{#issues-9-ea97cded1a7517c4a75e4c5e3dc04047a18d8a69}

- Commit number: ea97cded1a7517c4a75e4c5e3dc04047a18d8a69
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 00:48:22
- Message content:
```
#9 - minimal document upload client-side functionality


```
- Related patterns:
  + Issues: [#9](#issues-9)

### commit: Vendor Inventory (#8){#issues-9-7f4aafc864aed34a580169e9a17d6fb59d66a7cc}

- Commit number: 7f4aafc864aed34a580169e9a17d6fb59d66a7cc
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-12 19:29:14
- Message content:
```
Vendor Inventory (#8)

* adjust colWidths

* add inventory module and interface for #5

* add_offering button for UI

* add/edit functionality for inventory offerings

* #9 - minimal document upload client-side functionality

* create choices list

* adjust customer table colnames

* added quantity to inventory as well as input validation

* fix tests for #11
```
- Related patterns:
  + Issues: [#8](#issues-8), [#5](#issues-5), [#9](#issues-9), [#11](#issues-11)

## Issue: #11{#issues-11}

### commit: fix tests for #11{#issues-11-4110d6f4f76c7c8b190b5aa9ee8c12d30f773a98}

- Commit number: 4110d6f4f76c7c8b190b5aa9ee8c12d30f773a98
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 19:27:57
- Message content:
```
fix tests for #11


```
- Related patterns:
  + Issues: [#11](#issues-11)

### commit: Vendor Inventory (#8){#issues-11-7f4aafc864aed34a580169e9a17d6fb59d66a7cc}

- Commit number: 7f4aafc864aed34a580169e9a17d6fb59d66a7cc
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-12 19:29:14
- Message content:
```
Vendor Inventory (#8)

* adjust colWidths

* add inventory module and interface for #5

* add_offering button for UI

* add/edit functionality for inventory offerings

* #9 - minimal document upload client-side functionality

* create choices list

* adjust customer table colnames

* added quantity to inventory as well as input validation

* fix tests for #11
```
- Related patterns:
  + Issues: [#8](#issues-8), [#5](#issues-5), [#9](#issues-9), [#11](#issues-11)

## Issue: #12{#issues-12}

### commit: create orders-module js for #12{#issues-12-e11b5bee0c22e1839b3fb958649bfc379287d2cc}

- Commit number: e11b5bee0c22e1839b3fb958649bfc379287d2cc
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 19:30:03
- Message content:
```
create orders_module js for #12


```
- Related patterns:
  + Issues: [#12](#issues-12)

## Issue: #13{#issues-13}

### commit: Order Routes (#13){#issues-13-e5b30be63f0768451673c54daf907b8162f22305}

- Commit number: e5b30be63f0768451673c54daf907b8162f22305
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-12 22:35:09
- Message content:
```
Order Routes (#13)

* remove data

* update orders module with new delivery map and table

* cleanup
```
- Related patterns:
  + Issues: [#13](#issues-13)

## Issue: #14{#issues-14}

### commit: add get-config.R (#14){#issues-14-d599eba18a3bc6a159ae9f0f606c2ea52cc10905}

- Commit number: d599eba18a3bc6a159ae9f0f606c2ea52cc10905
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-12 22:41:10
- Message content:
```
add get_config.R (#14)

* remove data

* update orders module with new delivery map and table

* cleanup

* add get_config.R script
```
- Related patterns:
  + Issues: [#14](#issues-14)

## Issue: #15{#issues-15}

### commit: Initial Deployment (#15){#issues-15-645987b96367b55db011a3fc0eda6f17687f518f}

- Commit number: 645987b96367b55db011a3fc0eda6f17687f518f
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-13 02:47:12
- Message content:
```
Initial Deployment (#15)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function
```
- Related patterns:
  + Issues: [#15](#issues-15), [#17](#issues-17)

## Issue: #17{#issues-17}

### commit: #17 - fix customers table and added utility function{#issues-17-a08259ba0bd8a8898882135b90e7a11e316a924b}

- Commit number: a08259ba0bd8a8898882135b90e7a11e316a924b
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-13 02:46:43
- Message content:
```
#17 - fix customers table and added utility function


```
- Related patterns:
  + Issues: [#17](#issues-17)

### commit: Initial Deployment (#15){#issues-17-645987b96367b55db011a3fc0eda6f17687f518f}

- Commit number: 645987b96367b55db011a3fc0eda6f17687f518f
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-13 02:47:12
- Message content:
```
Initial Deployment (#15)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function
```
- Related patterns:
  + Issues: [#15](#issues-15), [#17](#issues-17)

### commit: Miscellaneous (#18){#issues-17-d6735b78ac20bbaaba207688de4ac63d8e54d8b9}

- Commit number: d6735b78ac20bbaaba207688de4ac63d8e54d8b9
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-15 16:42:05
- Message content:
```
Miscellaneous (#18)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function

* dev misc

* add profile to docs

* add utils

* phone_input
```
- Related patterns:
  + Issues: [#18](#issues-18), [#17](#issues-17)

### commit: PowPolished and Enhancements (#22){#issues-17-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d}

- Commit number: dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-15 20:28:43
- Message content:
```
PowPolished and Enhancements (#22)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function

* dev misc

* add profile to docs

* add utils

* phone_input

* #20 - powpolished migration

powpolished changes and config

* bugfixes

* #21 - add customers mapping functionalities - still WIP but works
```
- Related patterns:
  + Issues: [#22](#issues-22), [#17](#issues-17), [#20](#issues-20), [#21](#issues-21)

## Issue: #18{#issues-18}

### commit: Miscellaneous (#18){#issues-18-d6735b78ac20bbaaba207688de4ac63d8e54d8b9}

- Commit number: d6735b78ac20bbaaba207688de4ac63d8e54d8b9
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-15 16:42:05
- Message content:
```
Miscellaneous (#18)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function

* dev misc

* add profile to docs

* add utils

* phone_input
```
- Related patterns:
  + Issues: [#18](#issues-18), [#17](#issues-17)

## Issue: #20{#issues-20}

### commit: #20 - powpolished migration{#issues-20-e6f7507591870173e588ab26458d77d8457ecc8c}

- Commit number: e6f7507591870173e588ab26458d77d8457ecc8c
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 20:24:03
- Message content:
```
#20 - powpolished migration

powpolished changes and config

```
- Related patterns:
  + Issues: [#20](#issues-20)

### commit: PowPolished and Enhancements (#22){#issues-20-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d}

- Commit number: dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-15 20:28:43
- Message content:
```
PowPolished and Enhancements (#22)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function

* dev misc

* add profile to docs

* add utils

* phone_input

* #20 - powpolished migration

powpolished changes and config

* bugfixes

* #21 - add customers mapping functionalities - still WIP but works
```
- Related patterns:
  + Issues: [#22](#issues-22), [#17](#issues-17), [#20](#issues-20), [#21](#issues-21)

## Issue: #21{#issues-21}

### commit: #21 - add customers mapping functionalities - still WIP but works{#issues-21-7df8ea4f55e3975e9df35a9b46633c379cb453fd}

- Commit number: 7df8ea4f55e3975e9df35a9b46633c379cb453fd
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 20:25:17
- Message content:
```
#21 - add customers mapping functionalities - still WIP but works


```
- Related patterns:
  + Issues: [#21](#issues-21)

### commit: PowPolished and Enhancements (#22){#issues-21-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d}

- Commit number: dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-15 20:28:43
- Message content:
```
PowPolished and Enhancements (#22)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function

* dev misc

* add profile to docs

* add utils

* phone_input

* #20 - powpolished migration

powpolished changes and config

* bugfixes

* #21 - add customers mapping functionalities - still WIP but works
```
- Related patterns:
  + Issues: [#22](#issues-22), [#17](#issues-17), [#20](#issues-20), [#21](#issues-21)

## Issue: #22{#issues-22}

### commit: PowPolished and Enhancements (#22){#issues-22-dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d}

- Commit number: dea8a6b980fb68af4e0fcd7d024ef9b1fb11432d
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-15 20:28:43
- Message content:
```
PowPolished and Enhancements (#22)

* deploy script

* artifacts from deploy script

* adminportal to vendorsdashboard

* add github and dockerhub registries to deployment

* fix polished version locally

* split out gcloud_deploy

* fix dockerhub push

* #17 - fix customers table and added utility function

* dev misc

* add profile to docs

* add utils

* phone_input

* #20 - powpolished migration

powpolished changes and config

* bugfixes

* #21 - add customers mapping functionalities - still WIP but works
```
- Related patterns:
  + Issues: [#22](#issues-22), [#17](#issues-17), [#20](#issues-20), [#21](#issues-21)

## Issue: No related issues{#issues-na}

### commit: Initial commit{#issues-na-1114084b1c3bfeb11e4b2405ee0afa46f25acaad}

- Commit number: 1114084b1c3bfeb11e4b2405ee0afa46f25acaad
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-02-17 22:32:29
- Message content:
```
Initial commit
```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: initial scaffolding{#issues-na-effe4b5adc89637414c8a7f3298c869612f3d8fa}

- Commit number: effe4b5adc89637414c8a7f3298c869612f3d8fa
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-10 01:01:13
- Message content:
```
initial scaffolding


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: ignore{#issues-na-e9b2289910fbe707e96ddc6fad26a9795aac7c29}

- Commit number: e9b2289910fbe707e96ddc6fad26a9795aac7c29
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-10 01:14:12
- Message content:
```
ignore


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: add maps{#issues-na-bac273d30c109dda0248d50d818f48d3dbc0134f}

- Commit number: bac273d30c109dda0248d50d818f48d3dbc0134f
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-10 20:50:07
- Message content:
```
add maps


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: online status - set to online for now{#issues-na-35bcc2aa31d86d4d8a210c7be26f324cdc98324a}

- Commit number: 35bcc2aa31d86d4d8a210c7be26f324cdc98324a
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 00:33:14
- Message content:
```
online status - set to online for now


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: minor cleanup{#issues-na-ba3c39d4ed6e166cd038824585e3b44bdb56d602}

- Commit number: ba3c39d4ed6e166cd038824585e3b44bdb56d602
- Author: merlinoa ; E-mail: andy.merlino@tychobra.com
- Date: 2021-03-11 02:27:28
- Message content:
```
minor cleanup

```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: adjust colWidths{#issues-na-d5222eb60799c58de67837c22bb47a8d07413a90}

- Commit number: d5222eb60799c58de67837c22bb47a8d07413a90
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 23:16:37
- Message content:
```
adjust colWidths


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: add-offering button for UI{#issues-na-002afe2d9bb7f27df62bbe52cf148b9075c4a1b7}

- Commit number: 002afe2d9bb7f27df62bbe52cf148b9075c4a1b7
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-11 23:20:30
- Message content:
```
add_offering button for UI


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: add/edit functionality for inventory offerings{#issues-na-6a8394f5db1b0f354a305608762bd795c373680d}

- Commit number: 6a8394f5db1b0f354a305608762bd795c373680d
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 00:23:37
- Message content:
```
add/edit functionality for inventory offerings


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: create choices list{#issues-na-981f81ef654e595e5bc6d392cac249d55727fb52}

- Commit number: 981f81ef654e595e5bc6d392cac249d55727fb52
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 19:25:50
- Message content:
```
create choices list


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: adjust customer table colnames{#issues-na-1888d7e592551be49fe66c6d13da1ac3be2046d8}

- Commit number: 1888d7e592551be49fe66c6d13da1ac3be2046d8
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 19:26:05
- Message content:
```
adjust customer table colnames


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: added quantity to inventory as well as input validation{#issues-na-35c0a10a3938b5963bcd53529757128183efb526}

- Commit number: 35c0a10a3938b5963bcd53529757128183efb526
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 19:27:06
- Message content:
```
added quantity to inventory as well as input validation


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: Merge branch 'develop' into main{#issues-na-294a43462dac134f0aa83520920b35165aba05d2}

- Commit number: 294a43462dac134f0aa83520920b35165aba05d2
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 19:30:17
- Message content:
```
Merge branch 'develop' into main


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: dev scripts{#issues-na-594972f104944203fc236cdc6d86e3f4b919b4fb}

- Commit number: 594972f104944203fc236cdc6d86e3f4b919b4fb
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 22:27:15
- Message content:
```
dev scripts


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: deploy script{#issues-na-a54e858721d62e71262d50f7e7d2019f9640c585}

- Commit number: a54e858721d62e71262d50f7e7d2019f9640c585
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 23:02:24
- Message content:
```
deploy script


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: artifacts from deploy script{#issues-na-3e39b7e7d1b230bfaa7394912681595d8f811079}

- Commit number: 3e39b7e7d1b230bfaa7394912681595d8f811079
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 23:03:13
- Message content:
```
artifacts from deploy script


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: adminportal to vendorsdashboard{#issues-na-4d5f28d2afa674b82021d2c61175784640f02503}

- Commit number: 4d5f28d2afa674b82021d2c61175784640f02503
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 23:04:45
- Message content:
```
adminportal to vendorsdashboard 


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: add github and dockerhub registries to deployment{#issues-na-9fb77746b2acf7f1357ef821ef05a171eab95b41}

- Commit number: 9fb77746b2acf7f1357ef821ef05a171eab95b41
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 23:49:17
- Message content:
```
add github and dockerhub registries to deployment


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: fix polished version locally{#issues-na-674ca4fb5d65783036a60e3ca516f4e84ff4933a}

- Commit number: 674ca4fb5d65783036a60e3ca516f4e84ff4933a
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 23:49:27
- Message content:
```
fix polished version locally


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: Update README.md{#issues-na-edfbc40b2d217f6057cff0d9b73d9e1c0856f331}

- Commit number: edfbc40b2d217f6057cff0d9b73d9e1c0856f331
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-12 23:53:14
- Message content:
```
Update README.md
```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: split out gcloud-deploy{#issues-na-1e783375c71e11c1a9dab6a6b7343fc5c71ded69}

- Commit number: 1e783375c71e11c1a9dab6a6b7343fc5c71ded69
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-12 23:54:49
- Message content:
```
split out gcloud_deploy


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: fix dockerhub push{#issues-na-bc6864ad53307cefc1d076a85d0eb58be00d5ee7}

- Commit number: bc6864ad53307cefc1d076a85d0eb58be00d5ee7
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-13 02:45:24
- Message content:
```
fix dockerhub push


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: dev misc{#issues-na-58fc0c3780117e4ed68b0602a5775998ea1ae1e1}

- Commit number: 58fc0c3780117e4ed68b0602a5775998ea1ae1e1
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 16:28:55
- Message content:
```
dev misc


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: add profile to docs{#issues-na-c9e587c536f5e0b84a0715f2d2cee304043aea3b}

- Commit number: c9e587c536f5e0b84a0715f2d2cee304043aea3b
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 16:39:49
- Message content:
```
add profile to docs


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: add utils{#issues-na-5dc128845ff51408c5b239efdcab458f6fd32dca}

- Commit number: 5dc128845ff51408c5b239efdcab458f6fd32dca
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 16:39:57
- Message content:
```
add utils


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: phone-input{#issues-na-fd52f8fab9e2b7abc275c543e1af5e417871a77c}

- Commit number: fd52f8fab9e2b7abc275c543e1af5e417871a77c
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 16:40:03
- Message content:
```
phone_input


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: for merge conflicts{#issues-na-191274e01a49bd852c771fe8384b7d7a1e4678b3}

- Commit number: 191274e01a49bd852c771fe8384b7d7a1e4678b3
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 16:41:21
- Message content:
```
for merge conflicts


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: bugfixes{#issues-na-65a5faa7faac51cc434a10241b7dccd6f0146f69}

- Commit number: 65a5faa7faac51cc434a10241b7dccd6f0146f69
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 20:24:17
- Message content:
```
bugfixes


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: Merge branch 'main' into develop{#issues-na-f43ee8c955492e816db2b08921dc437984859ed7}

- Commit number: f43ee8c955492e816db2b08921dc437984859ed7
- Author: GitHub ; E-mail: noreply@github.com
- Date: 2021-03-15 20:28:26
- Message content:
```
Merge branch 'main' into develop
```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: Merge remote-tracking branch 'origin/main' into main{#issues-na-277d80c13fdfd3f44304e3144140f2a2f447cdf2}

- Commit number: 277d80c13fdfd3f44304e3144140f2a2f447cdf2
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 20:29:30
- Message content:
```
Merge remote-tracking branch 'origin/main' into main


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: error from merge{#issues-na-b4d581b98f2754bd2e4c3d13601e82363b37c83f}

- Commit number: b4d581b98f2754bd2e4c3d13601e82363b37c83f
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 20:31:32
- Message content:
```
error from merge


```
- Related patterns:
  + Issues: [No related issues](#issues-na)

### commit: Merge branch 'develop' into main{#issues-na-8215dba365aee50a105e67b9b2b1fa1a4cd7b173}

- Commit number: 8215dba365aee50a105e67b9b2b1fa1a4cd7b173
- Author: Jimmy Briggs ; E-mail: jimmy.briggs@tychobra.com
- Date: 2021-03-15 20:31:51
- Message content:
```
Merge branch 'develop' into main


```
- Related patterns:
  + Issues: [No related issues](#issues-na)
